apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
  labels:
    app: go-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
      - name: go-api
        image: 34.118.202.127.nip.io/project2/go-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        - containerPort: 50051
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "weather-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
        - name: RABBITMQ_ADDR
          value: "amqp://guest:guest@rabbitmq.rabbitmq.svc.cluster.local:5672/"
        readinessProbe:
          tcpSocket:
            port: 50051
          initialDelaySeconds: 5
          periodSeconds: 10