FROM golang:1.24 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY internal/rabbitmq/ internal/rabbitmq/
COPY rabbitmq-consumer/ rabbitmq-consumer/
RUN CGO_ENABLED=0 GOOS=linux go build -o rabbitmq-consumer ./rabbitmq-consumer

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/rabbitmq-consumer .
CMD ["./rabbitmq-consumer"]