FROM golang:1.24 AS builder
WORKDIR /app
COPY . .
RUN apt-get update && apt-get install -y \
    librdkafka-dev \
    && rm -rf /var/lib/apt/lists/*
RUN CGO_ENABLED=1 GOOS=linux go build -o consumer ./consumer

FROM debian:bookworm-slim
WORKDIR /app
RUN apt-get update && apt-get install -y \
    librdkafka1 \
    && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/consumer .
CMD ["./consumer"]